FROM quay.io/geofeedia/base:debian
MAINTAINER Geofeedia <https://geofeedia.com>

# install kubectl binary
RUN curl -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.2.2/bin/linux/amd64/kubectl && \
    chmod 755 /usr/bin/kubectl
    
COPY drone-k8s /usr/bin/drone-k8s

ENTRYPOINT [ "drone-k8s" ]

